### ISSUE TITLE
MMM-NetworkSanner IPv6

### ISSUE THREAD

**Issue by Sennahoj82** [ianperrin/MMM-NetworkScanner#10]
Hello.

The module itself is great and works well with IPv4.
The problem is, though, that operation with IPv6 doesn't work. The module finds neither IP not MAC address in the network.
Is it possible to update the Module to IPv6?

Thanks.

**Comment by kyle-kelly** [comment]
@Sennahoj82 As far as I understand it's not yet possible. This module relies on arp-scan which uses ARP in IPv4 but has since been replaced by NDP in IPv6.

Basically we're waiting on an arp-scan equivalent for IPv6...however this might never come. The address space for IPv6 is so large it would take years to search. (See here)[https://www.internetsociety.org/blog/2015/02/ipv6-security-myth-4-ipv6-networks-are-too-big-to-scan/] for more.

**Comment by ianperrin** [comment]
Thanks @kyle-kelly - I think we can chalk this up as something which won’t be implemented
